#!/usr/bin/env bash
# Installs nginx with the following configurations:
#+ returns a page containing "hello world"
#+ listen to port 8080
#+ configures /redirect_me as a "301 Moved Permanently"
#+ includes a custom 404 page containing "Ceci n'est pas une page"
#+ contains a custom HTTP header named X-Served-By
#+ The value of the HTTP header is the hostname of the running server.

apt-get update
apt-get install -y nginx

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
touch /var/www/html/404.html
echo "C'est n'est pas une page" > /var/www/html/404.html

printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	add_header X-Served-By $HOSTNAME;
	root  /var/www/html;
	index index.html index.htm;

	location /redirect_me {
		return 301 http://youtube.com
	}

	error_page 404 /404.html;
	location /404 {
		root /var/www/html;
		internal;
	}
}" > /etc/nginx/sites-available/default;

service nginx restart1
