#!/usr/bin/env bash
#Installs HAProxy wit the following configurations:
#+ Enables management via the init script.
#+ Distributes requests using a round-robin algorithm.

apot-get install -y software-properties-common
add-get-repository -y ppa:vbernat/haproxy-1.8
apt-get update
apt-get install -y haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

print %s "global
	log 127.0.0.1 local0 notice
	maxconn 2000
	user haproxy
	group haproxy

defaults
	log  global
	mode http
	option dontlognull
	retries 3
	option redispatch
	timeout connect 5000
	timeout client 10000
	timeout server 10000

listen hbnb
	bind 0.0.0.0:80
	mode http
	stats enable
	stat uri /haproxy?stats
	balance roundrobin
	option httpclose
	option forwardfor
	server 162043-web-01 100.25.160.58 check
	server 162043-web-02 54.162.1.125 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start

